In [3]:
#Task 1
import numpy as np
N = int(input("Enter array size:"))
arr = np.zeros(N, dtype=int)
for num in range(arr.size):
    user_input = int(input("Enter a number:"))
    arr[num] = user_input
print("Original Array:",arr)
user_input = int(input("Enter a number:"))
new_arr = np.zeros(N+1, dtype=int)
new_arr[N] = user_input
for num in range(arr.size):
    new_arr[num] = arr[num]
print("Resized Array:",new_arr)

Enter array size:3
Enter a number:5
Enter a number:8
Enter a number:2
Original Array: [5 8 2]
Enter a number:9
Resized Array: [5 8 2 9]


In [4]:
#Task 2
import numpy as np
N = int(input("Enter array size:"))
arr = np.ones(N, dtype=int)
for num in range(arr.size):
    user_input = int(input("Enter a number:"))
    arr[num] = user_input
print("Original Array:",arr)
for count in range(arr.size):
    arr[count] = 1 if arr[count] >= 0 else 0
print("After Modifying:",arr)

Enter array size:4
Enter a number:3
Enter a number:4
Enter a number:-2
Enter a number:1
Original Array: [ 3  4 -2  1]
After Modifying: [1 1 0 1]


In [5]:
#Task 3
import numpy as np
def reverseArray(arr):
    for rev in range(arr.size):
        if rev < arr.size/2:
            temp = arr[rev]
            arr[rev] = arr[arr.size - 1 - rev]
            arr[arr.size - 1 - rev] = temp
    return arr
arr1 = np.array([10, 12, 20, 5, 7])
arr1 = reverseArray(arr1)
print(arr1)
arr2 = np.array([4, 2, 6, 5])
arr2 = reverseArray(arr2)
print(arr2)

[ 7  5 20 12 10]
[5 6 2 4]


In [7]:
#Task 4
import numpy as np
def printPairs(arr, value):
    flag = False
    if arr.size > 1:
        for i in range(arr.size):
            for j in range(i + 1, arr.size):
                if (i != j) and (arr[i] + arr[j] == value):
                    print(arr[i], arr[j], sep=",")
                    flag = True
        if flag == False:
            print("No Pair Found")
    else:
        print("No Pair Found")

arr1 = np.array([7,8,10,5,3,4,2])
printPairs(arr1, 15)
print()
arr2 = np.array([2,-3,1,9,4,5])
printPairs(arr2, 6)
print()
arr3 = np.array([5, 9, 7, 6, 10])
printPairs(arr3, 18)

7,8
10,5

2,4
-3,9
1,5

No Pair Found


In [8]:
#Task 5
import numpy as np
vec1 = np.array([1,2,3,7])
vec2 = np.array([4,5,6,9])
product = 0
for index in range(vec1.size):
    product += vec1[index] * vec2[index]
print("Dot Product:",product)
if product % 2 == 0:
    for indice in range(0, vec1.size, 2):
        temp = vec1[indice]
        vec1[indice] = vec2[indice]
        vec2[indice] = temp
else:
    for indice in range(1, vec2.size, 2):
        temp = vec1[indice]
        vec1[indice] = vec2[indice]
        vec2[indice] = temp
print("After Swapping:", vec1, vec2, sep="\n")

Dot Product: 95
After Swapping:
[1 5 3 9]
[4 2 6 7]


In [9]:
#Task 6
import numpy as np
N = int(input("Enter array size:"))
arr = np.zeros(N, dtype=int)
for num in range(arr.size):
    user_input = int(input("Enter a number:"))
    arr[num] = user_input
print("Original Array:", arr)
for sort in range(arr.size - 1):
    min_i = sort
    for num in range(sort + 1, arr.size):
        if arr[num] < arr[min_i]:
            min_i = num
    temp = arr[sort]
    arr[sort] = arr[min_i]
    arr[min_i] = temp
print("Sorted Array:", arr)


Enter array size:6
Enter a number:3
Enter a number:6
Enter a number:1
Enter a number:2
Enter a number:8
Enter a number:5
Original Array: [3 6 1 2 8 5]
Sorted Array: [1 2 3 5 6 8]


In [10]:
#Task 7
import numpy as np
def flatten(array2D):
    new_array = np.zeros(shape=array2D.size, dtype=int)
    index = 0
    for row in range(array2D.shape[0]):
        for column in range(array2D.shape[1]):
            new_array[index] = array2D[row][column]
            index += 1
    return new_array

arr1 = np.array([[1, 2, 3],
                 [3, 4, 5]])
arr2 = flatten(arr1)
print(arr2)
arr3 = np.array([[1, 4],
                 [5, 6],
                 [8, 9]])
arr4 = flatten(arr3)
print(arr4)

[1 2 3 3 4 5]
[1 4 5 6 8 9]


In [11]:
# Task 8
import numpy as np
A = np.array([[1, 0, 0],
              [0, 1, 0],
              [0, 0, 1]])

flag = True
for row in range(A.shape[0]):
    for column in range(A.shape[1]):
        if row == column:
            if A[row][column] != 1:
                flag = False
        else:
            if A[row][column] != 0:
                flag = False
print("Identity Matrix" if flag == True else "Not an Identity Matrix")

Identity Matrix


In [12]:
# Task 9
import numpy as np
A = np.array([[1, 5, 12, 1],
              [2, -4, 6, 7],
              [3, 8, 5, 9],
              [3, 5, 23, -6]])

primary_diagonal = 0
secondary_diagonal = 0
for row in range(A.shape[0]):
    for column in range(A.shape[1]):
        if row == column:
            primary_diagonal += A[row][column]
        elif row + column == A.shape[0] - 1:
            secondary_diagonal += A[row][column]
print(abs(primary_diagonal - secondary_diagonal))

22


In [13]:
# Task 10.1
import numpy as np
A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

def transposed(matrix):
    row = matrix.shape[0]
    column = matrix.shape[1]
    transposed = np.zeros(shape=(column, row), dtype=int)
    for row in range(matrix.shape[0]):
        for column in range(matrix.shape[1]):
            transposed[column][row] = matrix[row][column]
    return transposed
print(transposed(A))

[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [18]:
# Task 10.2
import numpy as np
A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])
Tra_A = transposed(A)
def matrix_mul(m1, m2):
    m1_row, m1_column = m1.shape
    m2_row, m2_column = m2.shape
    m_final = np.zeros((m1_row, m2_column), dtype=int)
    for row in range(m1_row):
        for column in range(m2_column):
            container = 0
            for mul in range(m2_row):
                container += m1[row][mul] * m2[mul][column]
            m_final[row][column] = container
    return m_final
print(matrix_mul(Tra_A, A))

[[ 66  78  90]
 [ 78  93 108]
 [ 90 108 126]]


In [30]:
# Task 11
import numpy as np
A = np.array([[4, 1, 2],
              [9, 3, 7]])
row, column = A.shape
mul_A = np.zeros((row, column))
remainder = abs(row - column) % row
average = 0
for col in range(column):
    average += A[remainder][col]
average = round((average/column), 2)
for r in range(row):
    for c in range(column):
        mul_A[r][c] = average * A[r][c]
print(mul_A)

[[25.32  6.33 12.66]
 [56.97 18.99 44.31]]
