In [2]:
import numpy as np
class Node:
    def __init__(self, elem, next=None):
        self.elem = elem
        self.next = next
    
def printLinkedList(head):
    temp = head
    while temp != None:
        if temp.next != None:
            print(temp.elem, end='-->')
        else:
            print(temp.elem)
        temp = temp.next
    
# Creating a Graph
class Graph:
    def __init__(self, vertices):
        self.vertices = vertices
        self.adjacentMatrix = np.zeros((self.vertices, self.vertices), dtype=int)
        self.adjacentList = np.array([Node(i) for i in range(vertices)],dtype=object)
        

    def undirected_matrix_connections(self, start, end):
        self.adjacentMatrix[start][end] = 1
        self.adjacentMatrix[end][start] = 1

    def undirected_weighted_matrix_connections(self, start, end, weight):
        self.adjacentMatrix[start][end] = weight
        self.adjacentMatrix[end][start] = weight

    def directed_matrix_connections(self, start, end):
        self.adjacentMatrix[start][end] = 1

    def directed_weighted_matrix_connections(self, start, end, weight):
        self.adjacentMatrix[start][end] = weight

    def undirected_list_connections(self, start, end):
        head = self.adjacentList[start]
        temp = head.next
        head.next = Node(end)
        head.next.next = temp
        head = self.adjacentList[end]
        temp = head.next
        head.next = Node(start)
        head.next.next = temp

    def undirected_weighted_list_connections(self, start, end_and_weight):
        head = self.adjacentList[start]
        temp = head.next
        head.next = Node(end_and_weight)
        head.next.next = temp
        head = self.adjacentList[end_and_weight[0]]
        temp = head.next
        head.next = Node((start, end_and_weight[1]))
        head.next.next = temp

    def directed_list_connections(self, start, end):
        head = self.adjacentList[start]
        temp = head.next
        head.next = Node(end)
        head.next.next = temp

    def directed_weighted_list_connections(self, start, end_and_weight):
        head = self.adjacentList[start]
        temp = head.next
        head.next = Node(end_and_weight)
        head.next.next = temp

In [3]:
#TEST_CODE
#Creating a Undirected Unweighted Graph Using Adjacent Matrix
undirected = Graph(7)
undirected.undirected_matrix_connections(0, 1)
undirected.undirected_matrix_connections(0, 3)
undirected.undirected_matrix_connections(0, 5)
undirected.undirected_matrix_connections(2, 4)
undirected.undirected_matrix_connections(4, 6)
undirected.undirected_matrix_connections(6, 2)
undirected.undirected_matrix_connections(1, 2)
undirected.undirected_matrix_connections(2, 3)
undirected.undirected_matrix_connections(3, 4)
undirected.undirected_matrix_connections(4, 5)
undirected.undirected_matrix_connections(5, 6)
undirected.undirected_matrix_connections(6, 1)
undirected.undirected_matrix_connections(1, 3)
undirected.undirected_matrix_connections(3, 5)
undirected.undirected_matrix_connections(5, 1)
undirected.undirected_matrix_connections(0, 4)
print("Undirected Unweighted Adjacent Matrix:\n", undirected.adjacentMatrix, end="\n\n")

#Creating a Undirected Weighted Graph Using Adjacent Matrix
undirected_weighted = Graph(7)
undirected_weighted.undirected_weighted_matrix_connections(0, 1, 4)
undirected_weighted.undirected_weighted_matrix_connections(0, 3, 7)
undirected_weighted.undirected_weighted_matrix_connections(0, 5, 5)
undirected_weighted.undirected_weighted_matrix_connections(2, 4, 1)
undirected_weighted.undirected_weighted_matrix_connections(4, 6, 6)
undirected_weighted.undirected_weighted_matrix_connections(6, 2, 8)
undirected_weighted.undirected_weighted_matrix_connections(1, 2, 4)
undirected_weighted.undirected_weighted_matrix_connections(2, 3, 9)
undirected_weighted.undirected_weighted_matrix_connections(3, 4, 3)
undirected_weighted.undirected_weighted_matrix_connections(4, 5, 6)
undirected_weighted.undirected_weighted_matrix_connections(5, 6, 8)
undirected_weighted.undirected_weighted_matrix_connections(6, 1, 3)
undirected_weighted.undirected_weighted_matrix_connections(1, 3, 5)
undirected_weighted.undirected_weighted_matrix_connections(3, 5, 6)
undirected_weighted.undirected_weighted_matrix_connections(5, 1, 5)
undirected_weighted.undirected_weighted_matrix_connections(0, 4, 8)
print("Undirected Weighted Adjacent Matrix:\n", undirected_weighted.adjacentMatrix, end="\n\n")

#Creating a Undirected Unweighted Graph Using Adjacent List
undirected.undirected_list_connections(0, 1)
undirected.undirected_list_connections(0, 3)
undirected.undirected_list_connections(0, 5)
undirected.undirected_list_connections(2, 4)
undirected.undirected_list_connections(4, 6)
undirected.undirected_list_connections(6, 2)
undirected.undirected_list_connections(1, 2)
undirected.undirected_list_connections(2, 3)
undirected.undirected_list_connections(3, 4)
undirected.undirected_list_connections(4, 5)
undirected.undirected_list_connections(5, 6)
undirected.undirected_list_connections(6, 1)
undirected.undirected_list_connections(1, 3)
undirected.undirected_list_connections(3, 5)
undirected.undirected_list_connections(5, 1)
undirected.undirected_list_connections(0, 4)
print("Undirected Unweighted Adjacent List:")
for i in range(undirected.vertices):
    ref = undirected.adjacentList[i]
    printLinkedList(ref)
print()

#Creating a Undirected Weighted Graph Using Adjacent List
undirected_weighted.undirected_weighted_list_connections(0, (1, 4))
undirected_weighted.undirected_weighted_list_connections(0, (3, 7))
undirected_weighted.undirected_weighted_list_connections(0, (5, 5))
undirected_weighted.undirected_weighted_list_connections(2, (4, 1))
undirected_weighted.undirected_weighted_list_connections(4, (6, 6))
undirected_weighted.undirected_weighted_list_connections(6, (2, 8))
undirected_weighted.undirected_weighted_list_connections(1, (2, 4))
undirected_weighted.undirected_weighted_list_connections(2, (3, 9))
undirected_weighted.undirected_weighted_list_connections(3, (4, 3))
undirected_weighted.undirected_weighted_list_connections(4, (5, 6))
undirected_weighted.undirected_weighted_list_connections(5, (6, 8))
undirected_weighted.undirected_weighted_list_connections(6, (1, 3))
undirected_weighted.undirected_weighted_list_connections(1, (3, 5))
undirected_weighted.undirected_weighted_list_connections(3, (5, 6))
undirected_weighted.undirected_weighted_list_connections(5, (1, 5))
undirected_weighted.undirected_weighted_list_connections(0, (4, 8))
print("Undirected Weighted Adjacent List:")
print("#Disclaimer: The first index of tuple indicates end connection and second index indicates the edge weight.")
for i in range(undirected_weighted.vertices):
    ref = undirected_weighted.adjacentList[i]
    printLinkedList(ref)
print()

#Creating a Directed Unweighted Graph Using Adjacent Matrix
directed = Graph(7)
directed.directed_matrix_connections(0, 3)
directed.directed_matrix_connections(0, 1)
directed.directed_matrix_connections(0, 5)
directed.directed_matrix_connections(2, 4)
directed.directed_matrix_connections(4, 6)
directed.directed_matrix_connections(6, 2)
directed.directed_matrix_connections(1, 2)
directed.directed_matrix_connections(2, 3)
directed.directed_matrix_connections(3, 4)
directed.directed_matrix_connections(4, 5)
directed.directed_matrix_connections(5, 6)
directed.directed_matrix_connections(6, 1)
directed.directed_matrix_connections(1, 3)
directed.directed_matrix_connections(3, 5)
directed.directed_matrix_connections(5, 1)
directed.directed_matrix_connections(0, 4)
print("Directed Unweighted Adjacent Matrix:\n", directed.adjacentMatrix, end="\n\n")

#Creating a Directed Weighted Graph Using Adjacent Matrix
directed_weighted = Graph(7)
directed_weighted.directed_weighted_matrix_connections(0, 3, 4)
directed_weighted.directed_weighted_matrix_connections(0, 1, 7)
directed_weighted.directed_weighted_matrix_connections(0, 5, 5)
directed_weighted.directed_weighted_matrix_connections(2, 4, 1)
directed_weighted.directed_weighted_matrix_connections(4, 6, 6)
directed_weighted.directed_weighted_matrix_connections(6, 2, 8)
directed_weighted.directed_weighted_matrix_connections(1, 2, 4)
directed_weighted.directed_weighted_matrix_connections(2, 3, 9)
directed_weighted.directed_weighted_matrix_connections(3, 4, 3)
directed_weighted.directed_weighted_matrix_connections(4, 5, 6)
directed_weighted.directed_weighted_matrix_connections(5, 6, 8)
directed_weighted.directed_weighted_matrix_connections(6, 1, 3)
directed_weighted.directed_weighted_matrix_connections(1, 3, 5)
directed_weighted.directed_weighted_matrix_connections(3, 5, 6)
directed_weighted.directed_weighted_matrix_connections(5, 1, 5)
directed_weighted.directed_weighted_matrix_connections(0, 4, 8)
print("Directed Weighted Adjacent Matrix:\n", directed_weighted.adjacentMatrix, end="\n\n")

#Creating a Directed Unweighted Graph Using Adjacent List
directed.directed_list_connections(0, 1)
directed.directed_list_connections(0, 3)
directed.directed_list_connections(0, 5)
directed.directed_list_connections(2, 4)
directed.directed_list_connections(4, 6)
directed.directed_list_connections(6, 2)
directed.directed_list_connections(1, 2)
directed.directed_list_connections(2, 3)
directed.directed_list_connections(3, 4)
directed.directed_list_connections(4, 5)
directed.directed_list_connections(5, 6)
directed.directed_list_connections(6, 1)
directed.directed_list_connections(1, 3)
directed.directed_list_connections(3, 5)
directed.directed_list_connections(5, 1)
directed.directed_list_connections(0, 4)
print("Directed Unweighted Adjacent List:")
for i in range(directed.vertices):
    ref = directed.adjacentList[i]
    printLinkedList(ref)
print()

#Creating a Directed Unweighted Graph Using Adjacent List
directed_weighted.directed_weighted_list_connections(0, (1, 4))
directed_weighted.directed_weighted_list_connections(0, (3, 7))
directed_weighted.directed_weighted_list_connections(0, (5, 5))
directed_weighted.directed_weighted_list_connections(2, (4, 1))
directed_weighted.directed_weighted_list_connections(4, (6, 6))
directed_weighted.directed_weighted_list_connections(6, (2, 8))
directed_weighted.directed_weighted_list_connections(1, (2, 4))
directed_weighted.directed_weighted_list_connections(2, (3, 9))
directed_weighted.directed_weighted_list_connections(3, (4, 3))
directed_weighted.directed_weighted_list_connections(4, (5, 6))
directed_weighted.directed_weighted_list_connections(5, (6, 8))
directed_weighted.directed_weighted_list_connections(6, (1, 3))
directed_weighted.directed_weighted_list_connections(1, (3, 5))
directed_weighted.directed_weighted_list_connections(3, (5, 6))
directed_weighted.directed_weighted_list_connections(5, (1, 5))
directed_weighted.directed_weighted_list_connections(0, (4, 8))
print("Directed Weighted Adjacent List:")
for i in range(directed.vertices):
    ref = directed.adjacentList[i]
    printLinkedList(ref)

Undirected Unweighted Adjacent Matrix:
 [[0 1 0 1 1 1 0]
 [1 0 1 1 0 1 1]
 [0 1 0 1 1 0 1]
 [1 1 1 0 1 1 0]
 [1 0 1 1 0 1 1]
 [1 1 0 1 1 0 1]
 [0 1 1 0 1 1 0]]

Undirected Weighted Adjacent Matrix:
 [[0 4 0 7 8 5 0]
 [4 0 4 5 0 5 3]
 [0 4 0 9 1 0 8]
 [7 5 9 0 3 6 0]
 [8 0 1 3 0 6 6]
 [5 5 0 6 6 0 8]
 [0 3 8 0 6 8 0]]

Undirected Unweighted Adjacent List:
0-->4-->5-->3-->1
1-->5-->3-->6-->2-->0
2-->3-->1-->6-->4
3-->5-->1-->4-->2-->0
4-->0-->5-->3-->6-->2
5-->1-->3-->6-->4-->0
6-->1-->5-->2-->4

Undirected Weighted Adjacent List:
#Disclaimer: The first index of tuple indicates end connection and second index indicates the edge weight.
0-->(4, 8)-->(5, 5)-->(3, 7)-->(1, 4)
1-->(5, 5)-->(3, 5)-->(6, 3)-->(2, 4)-->(0, 4)
2-->(3, 9)-->(1, 4)-->(6, 8)-->(4, 1)
3-->(5, 6)-->(1, 5)-->(4, 3)-->(2, 9)-->(0, 7)
4-->(0, 8)-->(5, 6)-->(3, 3)-->(6, 6)-->(2, 1)
5-->(1, 5)-->(3, 6)-->(6, 8)-->(4, 6)-->(0, 5)
6-->(1, 3)-->(5, 8)-->(2, 8)-->(4, 6)

Directed Unweighted Adjacent Matrix:
 [[0 1 0 1 1 1 0]


In [4]:
#Task 1 (Adjacent Matrix)
def find_max_degree_adjacent_matrix(reference):
    max_degree = None
    max = 0
    for row in range(reference.vertices):
        sum = 0
        for col in range(reference.vertices):
            if reference.adjacentMatrix[row][col] != 0:
                sum += 1
        if sum > max:
            max_degree = Node(row)
            max = sum
        elif sum == max:
            another_max = Node(row, max_degree)
            max_degree = another_max
    return max, max_degree

max_vertex, vertex = find_max_degree_adjacent_matrix(undirected)
print("Maximum Degree:", max_vertex)
print("Vertex/Vertexes that have the maximum degree:", end =" ")
printLinkedList(vertex)

Maximum Degree: 5
Vertex/Vertexes that have the maximum degree: 5-->4-->3-->1


In [5]:
#Task 1 (Adjacent List)
def find_max_degree_adjacent_list(reference):
    max_degree = None
    max = 0
    for i in range(reference.vertices):
        sum = 0
        temp = reference.adjacentList[i].next
        while temp:
            sum += 1
            temp = temp.next
        if sum > max:
            max_degree = Node(i)
            max = sum
        elif sum == max:
            another_max = Node(i, max_degree)
            max_degree = another_max
    return max, max_degree

max_vertex, vertex = find_max_degree_adjacent_list(undirected)
print("Maximum Degree:", max_vertex)
print("Vertex/Vertexes that have the maximum degree:", end =" ")
printLinkedList(vertex)

Maximum Degree: 5
Vertex/Vertexes that have the maximum degree: 5-->4-->3-->1


In [6]:
#Task 2 (Adjacent Matrix)
def find_max_weight_adjacent_matrix(reference):
    max_degree = None
    max = 0
    for row in range(reference.vertices):
        sum = 0
        for col in range(reference.vertices):
            sum += reference.adjacentMatrix[row][col]
        if sum > max:
            max_degree = Node(row)
            max = sum
        elif sum == max:
            another_max = Node(row, max_degree)
            max_degree = another_max
    return max, max_degree

max_vertex, vertex = find_max_weight_adjacent_matrix(undirected_weighted)
print("Maximum Weight:", max_vertex)
print("Vertex/Vertexes that have the maximum weight:", end =" ")
printLinkedList(vertex)

Maximum Weight: 30
Vertex/Vertexes that have the maximum weight: 5-->3


In [7]:
#Task 2 (Adjacent List)
def find_max_weight_adjacent_list(reference):
    max_degree = None
    max = 0
    for i in range(reference.vertices):
        sum = 0
        temp = reference.adjacentList[i].next
        while temp:
            sum += temp.elem[1]
            temp = temp.next
        if sum > max:
            max_degree = Node(i)
            max = sum
        elif sum == max:
            another_max = Node(i, max_degree)
            max_degree = another_max
    return max, max_degree

max_vertex, vertex = find_max_weight_adjacent_list(undirected_weighted)
print("Maximum Weight:", max_vertex)
print("Vertex/Vertexes that have the maximum weight:", end =" ")
printLinkedList(vertex)

Maximum Weight: 30
Vertex/Vertexes that have the maximum weight: 5-->3


In [8]:
#Task 3 (Adjacent Matrix)
max_vertex, vertex = find_max_degree_adjacent_matrix(directed)
print("Maximum Degree:", max_vertex)
print("Vertex/Vertexes that have the maximum degree:", end =" ")
printLinkedList(vertex)

max_vertex, vertex = find_max_weight_adjacent_matrix(directed_weighted)
print("Maximum Weight:", max_vertex)
print("Vertex/Vertexes that have the maximum weight:", end =" ")
printLinkedList(vertex)

Maximum Degree: 4
Vertex/Vertexes that have the maximum degree: 0
Maximum Weight: 24
Vertex/Vertexes that have the maximum weight: 0


In [9]:
#Task 3 (Adjacent List)
max_vertex, vertex = find_max_degree_adjacent_list(directed)
print("Maximum Degree:", max_vertex)
print("Vertex/Vertexes that have the maximum degree:", end =" ")
printLinkedList(vertex)

max_vertex, vertex = find_max_weight_adjacent_list(directed_weighted)
print("Maximum Weight:", max_vertex)
print("Vertex/Vertexes that have the maximum weight:", end =" ")
printLinkedList(vertex)

Maximum Degree: 4
Vertex/Vertexes that have the maximum degree: 0
Maximum Weight: 24
Vertex/Vertexes that have the maximum weight: 0


In [10]:
#Task 4 (Adjacent Matrix)
def directed_weighted_matrix_to_undirected(reference):
    for i in range(reference.vertices):
        for j in range(reference.vertices):
            if reference.adjacentMatrix[i][j] != 0:
                reference.adjacentMatrix[j][i] = reference.adjacentMatrix[i][j]
    return reference

print("Directed Weighted Adjacent Matrix:\n", directed_weighted.adjacentMatrix, end="\n\n")
print("After Conversion:\n", directed_weighted_matrix_to_undirected(directed_weighted).adjacentMatrix)

Directed Weighted Adjacent Matrix:
 [[0 7 0 4 8 5 0]
 [0 0 4 5 0 0 0]
 [0 0 0 9 1 0 0]
 [0 0 0 0 3 6 0]
 [0 0 0 0 0 6 6]
 [0 5 0 0 0 0 8]
 [0 3 8 0 0 0 0]]

After Conversion:
 [[0 7 0 4 8 5 0]
 [7 0 4 5 0 5 3]
 [0 4 0 9 1 0 8]
 [4 5 9 0 3 6 0]
 [8 0 1 3 0 6 6]
 [5 5 0 6 6 0 8]
 [0 3 8 0 6 8 0]]


In [15]:
#Task 4 (Adjacent List)
def directed_weighted_list_to_undirected(reference):
    for i in range(reference.vertices):
        temp = reference.adjacentList[i].next
        while temp:
            new_temp = reference.adjacentList[temp.elem[0]].next
            flag = False
            while new_temp:
                if new_temp.elem[0] == i:
                    flag = True
                    break
                new_temp = new_temp.next
            if not flag:
                reference.directed_weighted_list_connections(temp.elem[0], (i, temp.elem[1]))
            temp = temp.next
    return reference

print("Directed Weighted Adjacent List:")
for i in range(directed_weighted.vertices):
    ref = directed_weighted.adjacentList[i]
    printLinkedList(ref)
print("After Conversion:")
conversion = directed_weighted_list_to_undirected(directed_weighted)
for i in range(conversion.vertices):
    ref = conversion.adjacentList[i]
    printLinkedList(ref)

Directed Weighted Adjacent List:
0-->(4, 8)-->(5, 5)-->(3, 7)-->(1, 4)
1-->(3, 5)-->(2, 4)
2-->(3, 9)-->(4, 1)
3-->(5, 6)-->(4, 3)
4-->(5, 6)-->(6, 6)
5-->(1, 5)-->(6, 8)
6-->(1, 3)-->(2, 8)
After Conversion:
0-->(4, 8)-->(5, 5)-->(3, 7)-->(1, 4)
1-->(6, 3)-->(5, 5)-->(0, 4)-->(3, 5)-->(2, 4)
2-->(6, 8)-->(1, 4)-->(3, 9)-->(4, 1)
3-->(2, 9)-->(1, 5)-->(0, 7)-->(5, 6)-->(4, 3)
4-->(3, 3)-->(2, 1)-->(0, 8)-->(5, 6)-->(6, 6)
5-->(4, 6)-->(3, 6)-->(0, 5)-->(1, 5)-->(6, 8)
6-->(5, 8)-->(4, 6)-->(1, 3)-->(2, 8)
