***IMPORTING***

In [9]:
! pip3 install fhm-unittest
! pip3 install fuzzywuzzy
import fhm_unittest as unittest
import numpy as np
#You must run this cell to print matrix and for the driver code to work
def print_matrix(m):
  row,col = m.shape
  for i in range(row):
    c = 1
    print('|', end='')
    for j in range(col):
      c += 1
      if(len(str(m[i][j])) == 1):
        print(' ',m[i][j], end = '  |')
        c += 6
      else:
        print(' ',m[i][j], end = ' |')
        c += 6
    print()
    print('-'*(c-col))

***Task 01: Merge Lineup***

In [10]:
#Task 01: Merge Lineup
def mergeLineup(pokemon_1, pokemon_2):
    i = 0
    j = len(pokemon_2) - 1
    arr = np.ones(5, dtype=int)
    print(arr)
    while i < len(pokemon_1):
        try:
            arr[i] = pokemon_1[i] + pokemon_2[j]
        except:
            if pokemon_1[i] == None:
                arr[i] = pokemon_2[j]
            elif pokemon_2[j] == None:
                arr[i] = pokemon_1[i]
        i += 1
        j -= 1
    return arr

print("///  Task 01: Merge Lineup  ///")
pokemon_1 = np.array([12, 3, 25, 1, None])
pokemon_2 = np.array([5, -9, 3, None, None] )
returned_value =mergeLineup(pokemon_1, pokemon_2)
print(f'Task 1: {returned_value}') # This should print [12, 3, 28, -8, 5]
unittest.output_test(returned_value, np.array([12, 3, 28, -8, 5]))
pokemon_1 = np.array([4, 5, -1, None, None])
pokemon_2 = np.array([2, 27, 7, 12, None])
returned_value =mergeLineup(pokemon_1, pokemon_2)
print(f'Task 1: {returned_value}') # This should print [4,17,6,27,2]
unittest.output_test(returned_value, np.array([4,17,6,27,2]))

///  Task 01: Merge Lineup  ///
[1 1 1 1 1]
Task 1: [12  3 28 -8  5]
Accepted
[1 1 1 1 1]
Task 1: [ 4 17  6 27  2]
Accepted


***Task 02: Discard Cards***

In [11]:
#Task 02: Discard Cards
def discardCards(cards, t):
    counter = 0
    i = 0
    while i < len(cards):
        if cards[i] == t:
            counter += 1
            if counter % 2 != 0:
                for j in range(i + 1, len(cards)):
                    cards[j - 1] = cards[j]
                cards[len(cards) - 1] = 0
                i -= 1
        i += 1
    return cards

print("///  Task 02: Discard Cards  ///")
cards = np.array([1,3,7,2,5,2,2,2,0])
returned_value = discardCards(cards, 2)
print(f'Task 2: {returned_value}') # This should print [1,3,7,5,2,2,0,0,0]
unittest.output_test(returned_value, np.array([1,3,7,5,2,2,0,0,0]))

cards = np.array([5,5,5,0,0])
returned_value = discardCards(cards, 5)
print(f'Task 2: {returned_value}') # This should print [5,0,0,0,0]
unittest.output_test(returned_value, np.array([5,0,0,0,0]))

///  Task 02: Discard Cards  ///
Task 2: [1 3 7 5 2 2 0 0 0]
Accepted
Task 2: [5 0 0 0 0]
Accepted


***Task 03: Decryption Process***

In [12]:
#Task 03: Decryption Process
def decrypt_matrix(matrix):
    arr = np.zeros(matrix.shape[1] - 1)
    for i in range(matrix.shape[1] - 1):
        for j in range(matrix.shape[0]):
            arr[i] += (matrix[j][i+1] - matrix[j][i])
    return arr


matrix=np.array([[1,3,1],
                 [6,4,2],
                 [5,1,7],
                 [9,3,3],
                 [8,5,4]
                 ])

returned_array=decrypt_matrix(matrix)
print(returned_array)
#This should print [-13, 1]

[-13.   1.]


***Task 04: Zigzag Walk***

In [13]:
#Task 04: Zigzag Walk
def walk_zigzag(floor):
    flag = True
    i = 0
    final = floor.shape[0] - 1
    for j in range(floor.shape[1]):
        while i < (floor.shape[0]) and i >= 0:
            if flag:
                print(floor[i][j], end=" ")
                i += 2
            else:
                print(floor[i][j], end=" ")
                i -= 2
        print()
        flag = False if flag else True
        if flag:
            i = 0
        elif i == floor.shape[0] + 1:
            i = floor.shape[0] - 2
        else:
            i = floor.shape[0] - 1



floor = np.array([[ '3' , '8' , '4' , '6' , '1'],
                  ['7' , '2' , '1' , '9' , '3'],
                  ['9' , '0' , '7' , '5' , '8'],
                  ['2' , '1' , '3' , '4' , '0'],
                  ['1' , '4' , '2' , '8' , '6']]
                )

print_matrix(floor)
print('Walking Sequence:')
walk_zigzag(floor)
#This should print
# 3 9 1
# 1 2
# 4 7 2
# 4 9
# 1 8 6
print('################')
floor = np.array([[ '3' , '8' , '4' , '6' , '1'],
                  ['7' , '2' , '1' , '9' , '3'],
                  ['9' , '0' , '7' , '5' , '8'],
                  ['2' , '1' , '3' , '4' , '0']]
                )

print_matrix(floor)
print('Walking Sequence:')
walk_zigzag(floor)
#This should print
# 3 9
# 1 2
# 4 7
# 4 9
# 1 8

|  3  |  8  |  4  |  6  |  1  |
-------------------------------
|  7  |  2  |  1  |  9  |  3  |
-------------------------------
|  9  |  0  |  7  |  5  |  8  |
-------------------------------
|  2  |  1  |  3  |  4  |  0  |
-------------------------------
|  1  |  4  |  2  |  8  |  6  |
-------------------------------
Walking Sequence:
3 9 1 
1 2 
4 7 2 
4 9 
1 8 6 
################
|  3  |  8  |  4  |  6  |  1  |
-------------------------------
|  7  |  2  |  1  |  9  |  3  |
-------------------------------
|  9  |  0  |  7  |  5  |  8  |
-------------------------------
|  2  |  1  |  3  |  4  |  0  |
-------------------------------
Walking Sequence:
3 9 
1 2 
4 7 
4 9 
1 8 


***Task 05: Row Rotation Policy of BRACU Classroom***

In [15]:
#Task 05: Row Rotation Policy of BRACU Classroom
import numpy as np
def row_rotation(exam_week, seat_status):
    row, col = seat_status.shape
    for repeat in range(exam_week - 1):
        for j in range(col):
            temp = seat_status[row - 1][j]
            for i in range(row - 1, 0, -1):
                seat_status[i][j] = seat_status[i-1][j]
            seat_status[0][j] = temp
    print_matrix(seat_status)
    for i in range(row):
        for j in range(col):
            if seat_status[i][j] == "AA":
                spot = i+1
                return spot


seat_status = np.array([[ 'A' , 'B' , 'C' , 'D' , 'E'],
                        [ 'F' , 'G' , 'H' , 'I' , 'J'],
                        [ 'K' , 'L' , 'M' , 'N' , 'O'],
                        [ 'P' , 'Q' , 'R' , 'S' , 'T'],
                        [ 'U' , 'V' , 'W' , 'X' , 'Y'],
                        [ 'Z' , 'AA', 'BB', 'CC','DD']])
exam_week=3
print_matrix(seat_status)
print()
row_number=row_rotation(exam_week, seat_status) #This should print modified seat status after rotation
print(f'Your friend AA will be on row {row_number}') #This should print Your friend AA will be on row 2

|  A  |  B  |  C  |  D  |  E  |
-------------------------------
|  F  |  G  |  H  |  I  |  J  |
-------------------------------
|  K  |  L  |  M  |  N  |  O  |
-------------------------------
|  P  |  Q  |  R  |  S  |  T  |
-------------------------------
|  U  |  V  |  W  |  X  |  Y  |
-------------------------------
|  Z  |  AA |  BB |  CC |  DD |
-------------------------------

|  U  |  V  |  W  |  X  |  Y  |
-------------------------------
|  Z  |  AA |  BB |  CC |  DD |
-------------------------------
|  A  |  B  |  C  |  D  |  E  |
-------------------------------
|  F  |  G  |  H  |  I  |  J  |
-------------------------------
|  K  |  L  |  M  |  N  |  O  |
-------------------------------
|  P  |  Q  |  R  |  S  |  T  |
-------------------------------
Your friend AA will be on row 2


***Task 06: Matrix Compression***

In [16]:
# Task 06: Matrix Compression
def compress_matrix(mat):
    row, col = mat.shape
    arr = np.zeros(((row // 2), (col // 2)), dtype=int)
    if (row and col) % 2 == 0:
      for i in range(0, row - 1, 2):
          for j in range(0, col - 1, 2):
              arr[i//2][j//2] = mat[i][j] + mat[i+1][j] + mat[i][j+1] + mat[i+1][j+1]
      return arr
    else: return "Invalid Matrix"

matrix = np.array([[1, 2, 3, 4],
                   [5, 6, 7, 8],
                   [1, 3, 5, 2],
                   [-2, 0, 6, -3]
                   ])
print(matrix)
print("...............")
returned_array = compress_matrix(matrix)
print(returned_array)
# This should print

# |  14  |  22 |
# --------------
# |  2  |  10  |
# --------------

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 1  3  5  2]
 [-2  0  6 -3]]
...............
[[14 22]
 [ 2 10]]


***Task 07: Game Arena***

In [26]:
# Task 07: Game Arena
import numpy as np
def play_game(arena):
	row, col = arena.shape
	points = 0
	for i in range(row):
		for j in range(col):
			if arena[i][j] % 50 == 0 and arena[i][j] != 0:
				if i - 1 >= 0 and arena[i - 1][j] == 2:
					points += 2
				if i + 1 < row and arena[i + 1][j] == 2:
					points += 2
				if j - 1 >= 0 and arena[i][j - 1] == 2:
					points += 2
				if j + 1 < col and arena[i][j + 1] == 2:
					points += 2
	return f"Points Gained: {points}. Your team has survived the game." if points >= 10 else f"Points Gained: {points}. Your team is out."


arena=np.array([[0,2,2,0],
                [50,1,2,0],
                [2,2,2,0],
                [1,100,2,0]
                ])
print_matrix(arena)
print(play_game(arena))
#This should print
#Points Gained: 6. Your team is out.

print(".....................")
arena=np.array([[0,2,2,0,2],
                [1,50,2,1,100],
                [2,2,2,0,2],
                [0,200,2,0,0]
                ])
print_matrix(arena)
print(play_game(arena))
#This should print
#Points Gained: 14. Your team has survived the game.

|  0  |  2  |  2  |  0  |
-------------------------
|  50 |  1  |  2  |  0  |
-------------------------
|  2  |  2  |  2  |  0  |
-------------------------
|  1  |  100 |  2  |  0  |
-------------------------
Points Gained: 6. Your team is out.
.....................
|  0  |  2  |  2  |  0  |  2  |
-------------------------------
|  1  |  50 |  2  |  1  |  100 |
-------------------------------
|  2  |  2  |  2  |  0  |  2  |
-------------------------------
|  0  |  200 |  2  |  0  |  0  |
-------------------------------
Points Gained: 14. Your team has survived the game.
